---
title: Design of distance sampling surveys
author: Centre for Research into Ecological and Environmental Modelling <br> **University of St Andrews**
date-modified: "November 2024"
date-format: "MMMM YYYY"
bibliography: ../references.bib
csl: ../../style/apa.csl
---

:::{.callout-warning collapse=false appearance='default' icon=true}
# Design of distance sampling surveys
### Distance for Windows exercise Solution
:::

## Systematic parallel line aerial survey of marine mammals in St Andrews bay

I derived the following results (yours will be slightly different because the survey locations in each simulation are selected at random). See also the project archived in [StAndrewsSolutions.zip](StAndrewsSolutions.zip)

| Trackline spacing | On effort trackline length (min) |  max     |     mean      | Total trackline length (min) |  max     |   mean        |
|-------------------|----------------------------|-------|-----------|------------------------|-------|-----------|
| 4.5               | 206.6                      | 228.8 | 219.6     | 249.3                  | 275.3 | 264.7     |
| 5.0               | 184.4                      | 205.6 | **198.2** | 220.5                  | 248.8 | **242.5** |
| 5.5               | 169.7                      | 189.5 | 178.9     | 217.1                  | 245.3 | 224.7     |
| 6.0               | 152.8                      | 176.1 | 162.1     | 183.7                  | 220.7 | 206.1     |

Based on these, the 5.0km spacing seems to get us closest to our goal of 200km on effort for 250km total trackline length. The maximum total trackline length did not exceed 250km which is re-assuring if this is an absolute upper limit.

I generated one realization of this 5km design, which we will use as the survey plan. It gave me a total trackline of 226.2km, with 184.6km on effort (see [StAndrewsSolutions.zip](StAndrewsSolutions.zip) project file). While this is rather less than I wanted, I can not validly throw this one away and generate another as we could no longer validly claim to have a random start point (I would effectively only be choosing start points that lead to the amount of trackline length I want) and so would no longer have even coverage probability.

As an aside, it is also interesting to look at the proportion of the total survey time spent on effort – reported in Distance as the proportion on effort/total effort:

| Trackline spacing | Mean on effort / total effort |
|-------------------|-------------------------------|
| 4.5               | 0.83                          |
| 5.0               | 0.82                          |
| 5.5               | 0.80                          |
| 6.0               | 0.78                          |

Not surprisingly, the greater the spacing between tracklines, the smaller the proportion of time we spend on effort as we have to spend time flying between the transect lines.


# Point Transect Bird Survey in Tentsmuir Forest

The answers to the questions posed in the instructions steer you to be cautious in the unequal allocation of effort between strata. 

:::{.callout-tip}
## Answers

*What are the analysis implications of a design with unequal coverage?*

> As our two strata have different coverage we should analyse them separately. We therefore need to make sure that we have sufficient transects in each strata to perform an analysis - ideally 20. There are two reasons that we should analyse them separately. Our covered area will not be representative of the study area as a whole. If density is higher or lower in one strata than the other we will get a biased estimate of abundance for the area as a whole using the standard distance sampling estimators. Pooling robustness between the two strata will no longer apply and it may be the case that detection functions differ between the two strata. We will also no longer have a representative sample of observations across the entire study region.

:::

:::{.callout-tip}
## Answers

*What spacing was used in each strata to try and achieve the desired number of samplers? Did your survey achieve exactly the number of samplers you requested? How much does coverage differ between the two strata for this realisation?*

> A spacing of 751m was used in the main stratum and 218m in the Morton Lochs stratum - these values are calculated based on the stratum areas and should not vary between surveys generated from the same design. You may or may not have achieved the number of transects you requested, this will depend on the random start point calculated for your particular survey. There will also be some variability in coverage, my survey achieved a coverage of 5.7% in the main strata and 64.8% in the Morton Loch strata.
>
> This is an extreme example of unequal coverage between the strata.

:::


:::{.callout-tip}
## Answers
*View the design statistics. What is the minimum number of samplers you will achieve in each strata? Is this sufficient to complete separate analyses in each stratum?*

> My design statistics indicated I should achieve between 22 and 27 transects in the main stratum and between 12 and 18 in the Morton Lochs stratum. I might be a bit concerned about the possibility of only achieving 12 transects in the Morton Lochs stratum (remember I cannot just discard a survey due to the number of transects and generate another as it will affect my coverage properties). 
>
> Whether this is sufficient will depend on a number of things such as a) objectives of the study, b) number of detections per transect etc. Information from a pilot study would be useful to help decide how many transects are required as a minimum.

:::

:::{.callout-tip}
## Answers
*Does it appear that you that there is even coverage within strata?*

> The main strata looks to have fairly uniform coverage. The values appear to have such small levels of variability that the variability that is seen will be down to stochasticity as it is seen across the entire strata. The Morton Lochs strata we can see has areas of lower coverage around the edge of the study region. Because of the smaller area of this stratum the perimeter to area ratio for Morton Lochs is large; creating the potential for edge effects to manifest themselves. This grid is a bit too coarse to allow us to properly judge how much of an issue edge effects will be in this strata. It may be wise to re-run the coverage simulation with a finer coverage grid and more repetitions too. Edge effects could potentially be problematic in such small areas.

:::

A completed version of the Tentsmuir survey design project can be found in [Tentsmuir-solution.zip](Tentsmuir-solution.zip).
