---
title: Analysis of stratified data
author: Centre for Research into Ecological and Environmental Modelling <br> **University of St Andrews**
date-modified: "November 2024"
date-format: "MMMM YYYY"
bibliography: ../references.bib
csl: ../../style/apa.csl
---

:::{.callout-warning collapse=false appearance='default' icon=true}
# Analysis of stratified data
### Distance for Windows exercise Solution
:::

**Outline Solutions**

Example analyses, which were used in getting these solutions, and which are referred to below, are in the project file [Stratify solutions.zip](Stratify solutions.zip).

## Relevant results are in Analysis *Full geog stratification*

The AICs are 127.9 for the southern stratum and 187.9 for the northern stratum. Detection function model fits are adequate visually and by goodness-of-fit test. Sample sizes are relatively small but not alarmingly so. The southern stratum appears to have a much narrower effective strip width.

## Relevant results are in Analysis *Pooled f(0)*

The AIC for the pooled detection function fit is 318.72. The detection function model fit is adequate visually and by goodness-of-fit test. Because

$$\text{AIC for pooled f(0)=}318.72 > (127.9+187.9=315.8)$$

estimation of separate detection functions for each stratum is preferable, given the observed data.

## Relevant results are in Analysis “No stratification”.

The whale density estimate from the unstratified analysis is 15-25% larger than the corresponding estimates from *Full geog stratification* and *Pooled f(0)* above. See table of study area abundance estimates below. The reason is that the survey design was geographically stratified, with less survey effort in the north stratum, and this is being ignored in the unstratified analysis.  

| **Model**                	| **Num parameters** 	| **N** 	| **N LCL** 	| **N UCL** 	|
|--------------------------	|-------------------:	|-------	|----------:	|-----------	|
| Full geog stratification 	|                  4 	| 14954 	|      8420 	| 26559     	|
| Pooled f(0)              	|                  2 	| 16333 	|      8619 	| 30949     	|
| No stratification        	|                  2 	| 18868 	|     11164 	| 31888     	|


:::{.callout-note collapse=false appearance='default' icon=true}
## Cluster size differences between strata

What is **not included in this project** are cluster sizes of the observed minke whale groups (we didn’t want to clutter the analysis with that detail). However, there is a bit of a story in geographic variation in cluster sizes. Cluster densities are higher in the southern stratum, but transects from both strata are being treated as if they are representative of the whole survey region. This results in a positively biased cluster density for the region as a whole. In addition, cluster sizes are higher in the South stratum. The estimate of E(s) from the unstratified analysis is a positively biased estimate of E(s) for the North stratum and a negatively biased estimate of E(s) for the South stratum. When it is applied to both strata, it results in a positively biased estimate of whale abundance because the North stratum is much larger and contains roughly twice as many whales as the south stratum.
:::

:::{.callout-warning collapse=false appearance='default' icon=true}
## Moral
Do not perform analyses without taking the survey design into account.
:::
