---
title: Analysis of point transect survey data
author: Centre for Research into Ecological and Environmental Modelling <br> **University of St Andrews**
date-modified: "November 2024"
date-format: "MMMM YYYY"
bibliography: ../references.bib
csl: ../../style/apa.csl
---

:::{.callout-warning collapse=false appearance='default' icon=true}
# Analysis of point transect survey data
### Distance for Windows exercise Solution
:::

## Simulated point transect data

1. Results from selected model options; remember these are simulated data with a half normal detection function and true density 79.6:


| Key         | Adjustment  | terms | w(m) | $\hat{D}$ | %CV  | LCB | UCB |
|-------------|-------------|---|------|------|------|------|-------|
| Half-normal | None        | 0 | 34.2 | 79.6 | 12.6 | 62.1 | 102.1 |
| Half-normal | None        | 0 | 20   | 70.8 | 15.7 | 52   | 96.5  |
| Uniform     | Cosine      | 1 | 20   | 75   | 14.4 | 56.5 | 99.6  |
| Hazard-rate | None        | 0 | 20   | 62.4 | 18.7 | 43.2 | 90    |
| Neg Exp     | Simple poly | 1 | 20   | 73.1 | 29.2 | 41.5 | 128.6 |

We see a fair degree of variability between analyses--reliable analysis of point transect data is more difficult than for line transect data. We see greater loss in precision from truncating data relative to line transect sampling, but if we do not truncate data, different models can give widely differing estimates. For these data, the hazard-rate model
appears to have downward bias, and precision is very poor for the negative exponential model.

## Winter wren data analysis (with bonus species included)

2. Our analyses of the winter wren data produced the following estimated densities (territories ha<sup>-1</sup>). Three other species were surveyed in the field. Estimates of density for those species are in the table below, although the Distance for Windows projects are not included. Method 5 is territory mapping (which does not use distance sampling, and as you note has no measure of precision associated because it is akin to a census method).

| Method | Common Chaffinch | Great Tit | European Robin | Winter Wren |
| ------ | ---------------- | --------- | -------------- | ----------- |
|1 | 1.03 | 0.58 | 0.52 | 1.29 |
| CI | (0.74,1.43) | (0.36,0.94) | (0.26,1.06) | (0.80,2.11) |
| 2 | 0.90 | 0.22 | 0.60 | 1.02 |
| CI | (0.62,1.29) | (0.13,0.39) | (0.38,0.94)  |(0.80,1.32) |
| 3 | 0.71 | 0.26 | 0.82 | 1.21 |
| CI | (0.45,1.23) | (0.09,0.76) | (0.52,1.31) | (0.82,1.79) |
| 4 | 0.64 | 0.26 |0.69 | 1.07 |
| CI | (0.46,0.90) | (0.16,0.42) | (0.47,1.00) | (0.87,1.31) |
| 5 | 0.75 | 0.21 | 0.84 |  1.30 |

To obtain the above estimates, I used a truncation distance of 110m for methods 1 and 2, 92.5m for method 3, and 95m for method 4. For the wren data, I used the uniform key with two cosine adjustments for method 1, the hazard-rate model for methods 2 and 3, and the half-normal key with two Hermite polynomial adjustments for method 4.

Points to note about the wren data: the wren more than any of the other species showed evidence of observer avoidance. This didn’t cause too many difficulties, except that the model favoured by AIC for line transect sampling was the hazard-rate model, which had a very flat shoulder out to around 75m. It was implausible that detection was certain out to this distance, so that I selected a model with a slightly inferior AIC value, but with a more plausible fitted detection function. Analyses of the cue count data are necessarily rather subjective, as the data show substantial over-dispersion (a single bird may give many songbursts all from the same location during a five-minute count). In this circumstance, goodness-of-fit tests are very misleading, and care must be taken not to overfit the data.

## Savannah sparrow analysis

3. Good fits to the 1980 Savannah sparrow data were obtained by truncating at 55m. The half-normal detection function without adjustments fitted well, as did the uniform with cosine adjustments. The hazard-rate model performed less well. There was a marginal preference for fitting the detection function separately in each stratum as judged by AIC, but pooling distance data across strata might offer rather more robust estimation. The estimates of density in the table correspond to a half-normal detection function, fitted separately in each stratum, with a truncation distance of 55m.

For 1981, w=55m was again satisfactory. There was now a clear preference for estimating the detection function separately by stratum, but little to choose between the half-normal model and the uniform model with cosine adjustments. For comparability with 1980, I chose the half-normal model, although AIC showed a very marginal preference for uniform + cosine. (Again, the hazard-rate model provided less good fits overall.)

Estimated densities $\hat{D}$ (birds/ha) of Savannah sparrows


| Year | Pasture | $\hat{D}$ | LCB | UCB |
|------|---|------|------|------|
| 1980 | 1 | 1.43 | 0.94 | 2.18 |
|      | 2 | 4.12 | 3.15 | 5.38 |
|      | 3 | 2.35 | 1.72 | 3.2  |
|      | All   | 2.63 | 2.19 | 3.16 |
|      |               |   |      |      |      |
| 1981 | 0 | 1.39 | 0.82 | 2.36 |
|      | 1 | 0.52 | 0.27 | 1.03 |
|      | 2 | 1.7  | 1.07 | 2.71 |
|      | 3 | 1.35 | 0.81 | 2.26 |
|      | All   | 1.24 | 0.95 | 1.62 |
