---
title: Other approaches to dealing with g(0)<1
author: Centre for Research into Ecological and Environmental Modelling <br> **University of St Andrews**
date-modified: "November 2024"
date-format: "MMMM YYYY"
bibliography: references.bib
---

## Introduction

The lecture and exercises in this chapter of the workshop focus on Mark-Recapture Distance Sampling (MRDS) approaches for dealing with cases where detection at zero distance is not certain (i.e., $g(0)<1$).  This is partly because general software exists for analysis of these models in the form of the `mrds` `R` package (also implemented in Distance for Windows).

In this document provide pointers to alternative approaches that may be useful in some circumstances.  As a caveat, some of the material referenced is quite technical.

## Multiplier approaches to dealing with availability bias in line transect surveys

If a separate estimate of $g0$ is avilable then it can be incorporated as a "multiplier": $\hat{N} = \hat{g0} \times \hat{N}^*$ where $\hat{N}^*$ is the estimate of $N$ from a conventional or multiple covariate distance sampling analysis.  Variance can be estimated using the delta method.  Multiplers can readily be incorporated into analyses in the `mrds` package or in Distance for Windows.

One approach to estimating $g0$ for marine mammals is based on knowledge of average surfacing and dive times.  An early work on this is @McLaren1961 but this has been superseded by @Laake1997.  However, @Borchers2013 showed that these approaches can be very biased, and developed and demonstrated an improved formulation, based on the use of Hidden Markov models (HHMs).

## Markov modelling approaches

Distance sampling is traditionally modelled in one dimension: using perpendicular distances for line transct surveys.  In a series of papers, Borchers and colleagues showed that it can be viewed as a two-dimnensional process, with detection being a function of forward and perpendicular distances.  This leads to approaches that can potentially accommodate uncertain detection at zero perpendicular distance, even using single-platform data.  Relevant references are @Borchers2013, @Langrock2013 and @Borchers2015.  An `R` package that implements some of these methods is 
[hmltm](https://github.com/david-borchers/hmltm), although please note that this is a research-level output, not designed for general use.

## Duplicate uncertainty

In some situations, assignment of duplicate detections between platforms is not certain.  One situation where this can occur is aerial surveys where there are either two planes, one following the other, or a single plane with muliple cameras pointing in different directions.  In these circumstances the methods of @Stevenson2018 or @Borchers2020 may be useful.  These both are accompanied by research-level `R` packages: [palm](https://github.com/b-steve/palm) and [twoplane](https://github.com/david-borchers/twoplane2).

An alternative approach that involves a probabilistic approach to duplicate identification for aerial surveys is @Hiby1998.

## Other ways to view MRDS models

Alternative perspectives on full, point and limiting independence models are given by @MacKenzie2015 and @Pavanato2021.

## Cue counting

Cue counting is a potential approach to deal with $g(0)<1$ of aniamls.  Instead of surveying for animals, you can survey for a cue they produce (e.g., a whale blow rather than a whale) where detection at zero distance is certain.  However, a new problem then becomes obatining an estimate of cue rate.  Cue counting is covered elsewhere in the workshop.

## References
